version = "0.0.1"

[[target_files_meta]]
  file_path = "bucket.tf"
  checksum = "cb238a149a2c1f0d4920ba7ccf607e8e"

[[objects]]
  target_code = "resource \"aws_s3_bucket\" \"TestBucket\" {\n  bucket = var.test_bucket_name\n}"
  [objects.parsed_resource]
    resource_type = "aws.s3.Bucket"
    logical_name = "TestBucket"
    natural_language = "Name: ${test_bucket_name}"
    referenced_resources = []
    referenced_variables = ["test_bucket_name"]
    source_file_path = "bucket.sami"
    source_file_line = 1

[[objects]]
  target_code = "variable \"test_bucket_name\" {\n  type = string\n  default = \"test-bucket-br31m9\"\n}"
  [objects.parsed_variable]
    name = "test_bucket_name"
    natural_language = ""
    type = "string"
    default = "test-bucket-br31m9"
    source_file_path = "bucket.sami"
    source_file_line = 4
