name: Build binaries

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build for ${{ matrix.goos }} ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: 386
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.2"

      - name: Build binary
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o salami-${{ matrix.goos }}-${{ matrix.goarch }}
        working-directory: ./cli

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: salami-${{ matrix.goos }}-${{ matrix.goarch }}
          path: salami-${{ matrix.goos }}-${{ matrix.goarch }}
          if-no-files-found: error
