name: Release packages

on:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  update-homebrew:
    name: Update Homebrew Tap

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Salami repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
          path: salami

      - name: Checkout Salami homebrew repo
        uses: actions/checkout@v3
        with:
          repository: petrgazarov/homebrew-salami
          path: homebrew_salami
          token: ${{ secrets.HOMEBREW_SALAMI_GITHUB_TOKEN }}

      - name: Get Salami version
        id: get-salami-version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate Homebrew Tap
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo petrgazarov/salami "${{ steps.get-salami-version.outputs.version }}" -p 'salami*darwin*' -p 'salami*linux*' --skip-existing
          ls salami-${{ steps.get-salami-version.outputs.version }}-*
          echo "::endgroup::"

          for i in \
            "darwin x64    SALAMI_DARWIN_X64" \
            "darwin arm64  SALAMI_DARWIN_ARM64" \
            "linux  x64    SALAMI_LINUX_X64" \
            "linux  arm64  SALAMI_LINUX_ARM64" \
            ; do
            set -- $i
            OS="$1"
            ARCH="$2"
            ENV_VAR="$3"
            SHA256="$(sha256sum "salami-${{ steps.get-salami-version.outputs.version }}-${OS}-${ARCH}" | cut -f1 -d' ')"
            SHA256_VAR="${ENV_VAR}_SHA256"
            URL_VAR="${ENV_VAR}_URL"
            printf -v "${SHA256_VAR}" "%s" "${SHA256}"
            printf -v "${URL_VAR}" "%s" "https://github.com/petrgazarov/salami/releases/download/${{ steps.get-salami-version.outputs.version }}/salami-${{ steps.get-salami-version.outputs.version }}-${OS}-${ARCH}"
            echo "${OS}-${ARCH} SHA256: " "${!SHA256_VAR}"
            echo "${OS}-${ARCH} URL:    " "${!URL_VAR}"
          done

          envsubst '$SALAMI_VERSION,$SALAMI_DARWIN_X64_URL,$SALAMI_DARWIN_X64_SHA256,$SALAMI_DARWIN_ARM64_URL,$SALAMI_DARWIN_ARM64_SHA256,$SALAMI_LINUX_X64_URL,$SALAMI_LINUX_X64_SHA256,$SALAMI_LINUX_ARM64_URL,$SALAMI_LINUX_ARM64_SHA256' < "./salami/.github/templates/salami_tap_template.rb" > ./homebrew_salami/salami.rb

      - name: Commit updated formula
        working-directory: homebrew_salami
        run: |
          set -euo pipefail

          git config user.name petrgazarov
          git config user.email petrgazarov@gmail.com
          git add salami.rb
          echo "::group::git diff"
          git  --no-pager diff
          echo "::endgroup::"
          git commit -m "Brew formula update for Salami version ${{ steps.get-salami-version.outputs.version }}"

      - name: Push formula
        working-directory: homebrew_salami
        run: |
          set -euo pipefail

          git push origin HEAD:main

  update-chocolatey:
    name: Update Chocolatey Package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Salami repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
          path: salami

      - name: Checkout Salami chocolatey repo
        uses: actions/checkout@v3
        with:
          repository: petrgazarov/chocolatey-salami
          path: chocolatey_salami
          token: ${{ secrets.CHOCOLATEY_SALAMI_GITHUB_TOKEN }}

      - name: Get Salami version
        id: get-salami-version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Push tag to Salami chocolatey repo
        working-directory: chocolatey_salami
        run: |
          set -euo pipefail

          git config user.name petrgazarov
          git config user.email
          git tag -a "${{ steps.get-salami-version.outputs.version }}" -m "Chocolatey package update for Salami version ${{ steps.get-salami-version.outputs.version }}"
          git push origin "${{ steps.get-salami-version.outputs.version }}"
