name: Release Homebrew tap

on:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  update-homebrew_salami:
    name: Update Homebrew Tap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Salami repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
          path: salami

      - name: Checkout Salami homebrew repo
        uses: actions/checkout@v3
        with:
          repository: petrgazarov/homebrew-salami
          path: homebrew_salami
          token: ${{ secrets.HOMEBREW_SALAMI_GITHUB_TOKEN }}

      - name: Get Salami version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update Homebrew Tap
        run: |
          set -euo pipefail

          # Can simulate this by cloning petrgazarov/salami & petrgazarov/homebrew_salami to adjacent directories
          # and running from their parent:

          ./salami/.github/scripts/generate_homebrew_tap.sh "${{ steps.get_version.outputs.version }}" > ./homebrew_salami/salami.rb
      - name: Commit updated formula
        working-directory: homebrew_salami
        run: |
          set -euo pipefail

          git config user.name petrgazarov
          git config user.email petrgazarov@gmail.com
          git add salami.rb
          echo "::group::git diff"
          git  --no-pager diff
          echo "::endgroup::"
          git commit -m "Brew formula update for Salami version ${{ steps.get_version.outputs.version }}"
      - name: Push formula
        working-directory: homebrew_salami
        run: |
          set -euo pipefail

          git push origin HEAD:main
