name: Test Mac OS install

on:
  workflow_run:
    workflows: ["Release packages"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test_homebrew_install:
    name: Test Homebrew install

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tap Salami
        run: brew tap petrgazarov/salami

      - name: Install Salami
        run: brew install salami

      - name: Get latest release tag
        id: latest-tag
        run: |
          set -euo pipefail

          LATEST_TAG=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Verify Installation
        run: |
          set -euo pipefail

          version=$(salami version) || exit 1
          if [[ $version != "Salami version ${{ steps.latest-tag.outputs.tag }}" ]]; then
            echo "Version mismatch. Expected: Salami v${{ steps.latest-tag.outputs.tag }}, Got: $version"
            exit 1
          fi
