name: Test Linux install

on:
  workflow_run:
    workflows: ["Release packages"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test_homebrew_install:
    name: Test Homebrew install

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: salami-repo

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

      - name: Add Homebrew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Tap Salami
        run: brew tap petrgazarov/salami

      - name: Install Salami
        run: brew install salami

      - name: Get latest release tag
        id: latest-tag
        run: |
          set -euo pipefail

          LATEST_TAG=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Verify version
        run: |
          set -euo pipefail

          version=$(salami version) || exit 1
          if [[ $version != "Salami version ${{ steps.latest-tag.outputs.tag }}" ]]; then
            echo "Version mismatch. Expected: Salami v${{ steps.latest-tag.outputs.tag }}, Got: $version"
            exit 1
          fi

      - name: Verify compile
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: salami-repo/.github/scripts/verify-compile/run.sh salami-repo