# frozen_string_literal: true

# This file was generated by https://github.com/salami/salami/blob/master/.github/workflows/release_packages.yml
class Salami < Formula
  desc "Salami - Infrastructure as Natural Language"
  homepage "https://github.com/petrgazarov/salami"
  version "${SALAMI_VERSION}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "${SALAMI_DARWIN_X64_URL}"
      sha256 "${SALAMI_DARWIN_X64_SHA256}"
    end

    if Hardware::CPU.arm?
      url "${SALAMI_DARWIN_ARM64_URL}"
      sha256 "${SALAMI_DARWIN_ARM64_SHA256}"
    end

    def install
      if Hardware::CPU.intel?
        filename = File.basename("${SALAMI_DARWIN_X64_URL}")
        bin.install filename => "salami"
      end

      if Hardware::CPU.arm?
        filename = File.basename("${SALAMI_DARWIN_ARM64_URL}")
        bin.install filename => "salami"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${SALAMI_LINUX_ARM64_URL}"
      sha256 "${SALAMI_LINUX_ARM64_SHA256}"
    end

    if Hardware::CPU.intel?
      url "${SALAMI_LINUX_X64_URL}"
      sha256 "${SALAMI_LINUX_X64_SHA256}"
    end

    def install
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        filename = File.basename("${SALAMI_LINUX_ARM64_URL}")
        bin.install filename => "salami"
      end

      if Hardware::CPU.intel?
        filename = File.basename("${SALAMI_LINUX_X64_URL}")
        bin.install filename => "salami"
      end
    end
  end

  test do
    system "#{bin}/salami version"
  end
end